### ISSUE TITLE
Use domain presence in Privacy Badger yellow list as a feature?

### ISSUE THREAD

**Issue by Bender250** [dibollinger/CookieBlock-Consent-Classifier#1]
All cookies from this list are blocked according to Privacy Badger description: https://github.com/EFForg/privacybadger/blob/master/src/data/yellowlist.txt

**Comment by dibollinger** [comment]
Pretty sure this list is GPLv3 licensed, which isn't compatible with this project.

Though I guess you could just retrieve it via a HTTP GET. Really not sure what the legal situation is when you do stuff like that.
